### ISSUE TITLE
Publish binaries for Mac arm64 ( M1 )

### ISSUE THREAD

**Issue by ewianda** [google/oauth2l#173]
Please provide prebuilt ARM64 binaries for macOS (Apple Silicon) as part of the release assets. This will significantly improve the user experience for those running macOS on ARM64 systems.

**Comment by andyrzhao** [comment]
Oauth2l currently uses a Google-specific cloudbuild pipeline for publishing the artifacts, which I'm not extremely familiar with (I cannot even find the configuration at this point.) I have cut a new release v1.3.1 to attempt to trigger a new build since this has not build for almost 2 years now. If v1.3.1 succeeds, I will look into how to add ARM to the macOS build. (Alternatively, we can move the whole build system off of cloudbuild, and use native Github tooling, but that will also require more research on how we can store the artifacts besides manually uploading them to the release page, like we do for some other open source projects.) Stay tuned.

**Comment by ewianda** [comment]
Thanks for the update

**Comment by andyrzhao** [comment]
Happy to announce that pre-built arm64 binaries are now available for darwin starting with v1.3.2! Link at https://storage.googleapis.com/oauth2l/latest/darwin_arm64.tgz Will update the README shortly.
