### ISSUE TITLE
error with go 1.12 and go modules

### ISSUE THREAD

**Issue by ptone** [google/oauth2l#69]
'''
$ mkdir tooltest
ptone-macbookpro:tmp$ cd tooltest/
ptone-macbookpro:tooltest$ go mod init main
go: creating new go.mod: module main
ptone-macbookpro:tooltest$ go get github.com/google/oauth2l
ptone-macbookpro:tooltest$ go install github.com/google/oauth2l
can't load package: package github.com/google/oauth2l: unknown import path "github.com/google/oauth2l": cannot find module providing package github.com/google/oauth2l
'''

go version: go version go1.12.1 darwin/amd64

**Comment by DazWilkin** [comment]
Hey @ptone !

`go get github.com/google/oauth2l` is pulling the latest release [`0,9.0`](https://github.com/google/oauth2l/releases) which is the previous python version.

If you:
```
go get github.com/google/oauth2l@v0.9.0
ls -l $(go list -f '{{.Dir}}' -m github.com/google/oauth2l)
LICENSE.txt  MANIFEST.in  oauth2l  README.md  setup.py  tox.ini
``` 
You'll see the python rather than golang files and this can't be `go built` (sic.)

A solution is to get the latest commit:
```
go get github.com/google/oauth2l@cf46f2e826b1874ba6d03460abc2e8fe4ed4f42a
```

A better solution is for the project team to release a Golang version.

**Comment by andyrzhao** [comment]
Thanks for the suggestion @DazWilkin ! We just published an official Golang release at https://github.com/google/oauth2l/releases/tag/v1.0.0

Go modules should now be able to use v1.0.0 by default.
