### ISSUE TITLE
userinfo.emil does not convert to https://www.googleapis.com/auth/userinfo.email anymore

### ISSUE THREAD

**Issue by bgy36ww** [google/oauth2l#89]
I recently re-downloaded the oauth2l, and trying to get token for userinfo.email

But it keep complaining:

Error 400: invalid_scope
Some requested scopes were invalid. {invalid=[userinfo.email]}

**Comment by andyrzhao** [comment]
Hi there, this is a known issue. The problem was introduced by fixing https://github.com/google/oauth2l/issues/71, and was discussed in https://github.com/google/oauth2l/issues/88.

We need another fix to re-enable appending the prefix to "userinfo.email" (and not "email"). In the meantime, please use "--scope email" or the full scope name as workarounds. Sorry for the inconvenience!

**Comment by bgy36ww** [comment]
Thank you for the quick response. I will use --scope email in the mean time.
